### ISSUE TITLE
Error: marker was not found

### ISSUE THREAD

**Issue by kaleabteweld** [steambap/png-to-ico#15]
I tried this but I got this error

const fs = require("fs");
const pngToIco = require("png-to-ico");

var file =
  "C:\\.......\\Attack on Titan Final Season\\110531l.jpg";

pngToIco(file)
  .then((buf) => {
    fs.writeFileSync(
      "C:\\..........\\Attack on Titan Final Season\\app.ico",
      buf
    );
  })
  .catch((err) => {
    console.log(err);
  });

Error: marker was not found
    at decodeScan (D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\jpeg\node_modules\jpeg-js\lib\decoder.js:344:15)
    at constructor.parse (D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\jpeg\node_modules\jpeg-js\lib\decoder.js:804:29)
    at Object.decode [as image/jpeg] (D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\jpeg\node_modules\jpeg-js\lib\decoder.js:1096:11)
    at Jimp.parseBitmap (D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\core\dist\utils\image-bitmap.js:196:53)
    at Jimp.parseBitmap (D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\core\dist\index.js:431:32)
    at D:\APPS\wamp\www\MY\node\anime_folder\node_modules\@jimp\core\dist\index.js:373:15
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:63:3) {
  methodName: 'constructor'
}

**Comment by steambap** [comment]
Thank you for reporting this. It looks like it is a problem from JIMP: https://github.com/oliver-moran/jimp/issues/102

**Comment by steambap** [comment]
Can you try to manually convert the image to PNG format and then use this library? I don't think I have the knowledge and time to fix jpeg lib in JIMP.
