### ISSUE TITLE
Could not find MIME for Buffer <null> on nodejs

### ISSUE THREAD

**Issue by blubbll** [steambap/png-to-ico#4]
at Jimp.parseBitmap (/rbd/pnpm-volume/2b227406-9d2f-4472-aaaf-e9b44cc9e0ce/node_modules/.registry.npmjs.org/@jimp/core/0.5.3/node_modules/@jimp/core/dist/index.js:498:32)

    at /rbd/pnpm-volume/2b227406-9d2f-4472-aaaf-e9b44cc9e0ce/node_modules/.registry.npmjs.org/@jimp/core/0.5.3/node_modules/@jimp/core/dist/index.js:440:15

    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:525:3) methodName: 'constructor' }

**Comment by steambap** [comment]
Can you upload your png files somewhere so that I can take a look?

**Comment by blubbll** [comment]
now i got node:20454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)

(node:20454) UnhandledPromiseRejectionWarning: RangeError [ERR_INVALID_OPT_VALUE]: The value "720" is invalid for option "value"

    at checkInt (buffer.js:1274:11)

    at Buffer.writeUInt8 (buffer.js:1325:7)

    at createDirectory (/rbd/pnpm-volume/2b227406-9d2f-4472-aaaf-e9b44cc9e0ce/node_modules/.registry.npmjs.org/to-ico/1.1.5/node_modules/to-ico/index.js:32:6)

    at Promise.all.then.data (/rbd/pnpm-volume/2b227406-9d2f-4472-aaaf-e9b44cc9e0ce/node_modules/.registry.npmjs.org/to-ico/1.1.5/node_modules/to-ico/index.js:98:16)

    at <anonymous>

    at process._tickCallback (internal/process/next_tick.js:182:7)

(node:20454) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)

and it crashes the node process
sadly i got to use an older plugin until yours doesn't throw errors for me :/

//favicon
toIco([fs.readFileSync(`${process.env.PWD}/assets/logo.png`)]).
then(s=>{fs.writeFileSync(`${process.env.PWD}/assets/favico.ico`,s)});

![logo.png](https://user-images.githubusercontent.com/34196146/46582882-375e8000-ca4e-11e8-8c08-444780e70915.png)

**Comment by blubbll** [comment]
i actually somehow uploaded a wrong file as the input, it's working now. thanks for this script
